#!/bin/bash
cd /opt/data/input
if [ -f code ];
then
    mv code code.java
    sed -i '0,/class \([a-zA-Z0-9\/_]\+\)/s//class code/' code.java
    javac code.java
else
    echo "No source file" 1>&2
fi
